### ISSUE TITLE
Information about reverse engineering

### ISSUE THREAD

**Issue by sbusceti** [jimmyH/BeSIM#1]
Hi, congratulations for this very good job!
I have a question about the process of reverse engineering:
in udpserver.py I noticed this section
` mode = byte2>>4 `
or
`sensorinfluence = (byte3>>3) & 0xf`

the question is: how did you understand that we need to do a right shift to extract the data?
Why shift right by 3, then 2 then 1 ?
How did you understand what data need to be shifted?
Why after shift operation, there is an & operation ?

thanks

**Comment by jimmyH** [comment]
They are bit fields, so it's just extracting the bits:

- byte3:
  - 1 bit unknown
  - 4 bits sensor influence
  - 1 bit units
  - 1 bit advance
  - 1 bit unknown
- byte4:
  - 5 bits unknown
  - 1 bit boost
  - 1 bit command issued
  - 1 bit season

One of those is almost certainly the low battery indicator, the rest might be OpenTherm related (my boiler is not connected via OT so I can't test those).

**Comment by sbusceti** [comment]
> 
> They are bit fields, so it's just extracting the bits:
> 
> - byte3:
>   - 1 bit unknown
>   - 4 bits sensor influence
>   - 1 bit units
>   - 1 bit advance
>   - 1 bit unknown
> - byte4:
>   - 5 bits unknown
>   - 1 bit boost
>   - 1 bit command issued
>   - 1 bit season
> 
> One of those is almost certainly the low battery indicator, the rest might be OpenTherm related (my boiler is not connected via OT so I can't test those).

Thanks for explaination.
If you need OT data you can check my repository. (My boiler is in OT mode).
