### ISSUE TITLE
No connection when cloud in state "network busy"

### ISSUE THREAD

**Issue by sbusceti** [jimmyH/BeSIM#2]
Hi, did you also notice that wifibox wont send any udp message if cloud connection with besmart-home.com is broken?
I installed your server, redirect all traffic from wifibox to server's instance but nothing appens; wifibox continue to do loop 53(dns) requests to api.besmart-home.com. (I tried also with my kotlin server but it do the same).
I also tried to change dns resolution for api.besmart-home.com to IP of internal server, nothing changes..

Did you experience the same problem?

(how can I contact you in private?)

**Comment by jimmyH** [comment]
It should try and connect to api.besmart-home.com:80 to check if there is a firmware update available. My server listens on port 80 and just returns a hardcoded firmware version which (hopefully) matches what is currently running on the wifibox. So, I just port forward any requests to api.besmart-home.com to my server.

**Comment by sbusceti** [comment]
no progress here; my wifibox is stuck in dns request loop.
I tried everything: traffic redirect with port forward,dns rewrite, reset wifibox .. nothing.
I'm starting to think that my wifibox is broken :(

**Comment by jimmyH** [comment]
Does your wifibox try to connect to anything else apart from dhcp/dns?

**Comment by sbusceti** [comment]
no; with tcpdump I see only a lot of dns request to api.besmart-home.com.. it seems like an infinite loop of dns request and sometimes ntp also

**Comment by sbusceti** [comment]
Ok found it. It's my fault: had assigned a static ip to wifibox and its not working. Now I let dhcp assign and it works.
Thaks
